name = "datetime"
version = "1.7.1"
license = "MIT"
author = "Milan Curcic"
maintainer = "caomaco@gmail.com"
copyright = "2013-2020 datetime-fortran contributors"

[[test]]
name = "datetime_tests"
source-dir = "tests"
main = "datetime_tests.f90"
